### ISSUE TITLE
gauche.versionが足りない？

### ISSUE THREAD

**Issue by ryotakato** [Hamayama/f2arrmat#1]
はじめまして。
ちょうどほしいと思ってたタイミングで、リポジトリみつけまして、試してみました。

## 事象

モジュールを読み込もうとすると、下記エラーが発生します。
```
*** ERROR: unbound variable: version<=?
    While loading "./f2arrmat.scm" at line 84
    While compiling "./sample-f2arrmat.scm" at line 4: (use f2arrmat)
    While loading "./sample-f2arrmat.scm" at line 4
Stack Trace:
_______________________________________
```

f2arrmat.scmの中で、gauche.versionをuseしないといけないのではないでしょうか？

## 環境
* Ubuntu 18.04
* Gauche 0.9.7

よろしくお願い致します。

**Comment by Hamayama** [comment]
連絡ありがとうございます。
gauche.version の use を追加しました。

**Comment by ryotakato** [comment]
迅速な対応ありがとうございます！
確認できました。 closeします。
